### ISSUE TITLE
Compatibility updates for latest JNA

### ISSUE THREAD

**Issue by jwcharp** [steos/jnafilechooser#10]
With JNA 5.5.0

For this library to still work you must update getString(0,true) calls
to getWideString(0)

**Comment by steos** [comment]
Thanks for the heads up! PRs are welcome :-)

**Comment by jwcharp** [comment]
One issue I am having is presetting the name and extension for a SAVE dialog. Any Ideas how I can accomplish this?

**Comment by jwcharp** [comment]
Is there any easy way to make the Window Directory Selector look like a standard File explorer as well? I'm struggling with that one. Might have to build a new DLL?

**Comment by dennisfabri** [comment]
I have updated my pull request, which will address this issue.
