### ISSUE TITLE
Set Initial Directory

### ISSUE THREAD

**Issue by santimchp** [steos/jnafilechooser#17]
Just wondering, is there a way of setting the initial directory when opening the dialog chooser? as it always opens c:/users/ by default. I didn't see any method for it so I was wondering if there is a way to do this. Thank you.

**Comment by mininotallarines** [comment]
Hey @santimchp this might be little late and I can't confirm this works but looking through the code, there is a constructor that takes a **`File`**`currentDirectory` and there is also a constructor that takes a **`String`**`currentDirectoryPath`
