### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by ikholiavko** [steos/jnafilechooser#5]
Hi.
We need a new release version to update this dependency correctly.
Could you please create new release version with this dependency update?
Thank you!

**Comment by steos** [comment]
Hi,
I'm not sure I follow. You mean bump the artifact version? There never was a release version, this has always been at 0.1-SNAPSHOT. I'd be happy to help if you can clarify, or just send me a pull request and I'll merge it.

thanks!

**Comment by ikholiavko** [comment]
Hi.
I created pull request for creating new release.
Thank you!

**Comment by ikholiavko** [comment]
Hello again. 
Unfortunately by pull request release tags does not apply to master branch.
Could you please create release based on commit 22c717cae439e1d12cafca3b28c9d09c544f1b2b.
Use next instruction:
Select  **0 releases** -> **Draft a new release** 
Then select **Chose or create tag** create tag e.g. v1.0
Select **target** -> **resent commits** and select commit 22c717cae439e1d12cafca3b28c9d09c544f1b2b "_Changet version to 1.0_"
Add **Title** and **description** (Not necessary). 
And press **Publish release**

Thank you for your help!

**Comment by steos** [comment]
I just created the release. Thanks!
